name: TeamPlugin
version: ${project.version}
api-version: 1.19
author: Zeron
main: com.neon.team.MainCore
libraries:
  - io.github.monun:tap-core:4.7.3
  - io.github.monun:kommand-core:2.14.0
  - io.github.monun:invfx-core:3.2.0
  - org.jetbrains.kotlinx:kotlinx-coroutines-core:1.6.4
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-api:2.9.0
  - com.github.shynixn.mccoroutine:mccoroutine-bukkit-core:2.9.0